forum/config/routes.rb
Rails.application.routes.draw do

  get 'profiles/new'

  get 'profiles/edit'

  get 'profiles/show'

  get 'profiles/upgradeUser'

  root 'groups#index'

  resources :groups do
    resources :posts
  end

  resources :profiles
  devise_for :users, controllers: { registrations: "registrations" }

  get 'pages/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

forum/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

forum/app/models/group.rb
class Group < ApplicationRecord
  has_many :posts
  accepts_nested_attributes_for :posts, allow_destroy: true, reject_if: :reject_posts

  def reject_posts(attributes)
  	attributes['title'].blank? && attributes['content'].blank?
  end
end

forum/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :group
  belongs_to :profile
  validates :title, presence: true, length: { minimum: 5 }
  validates :content, presence: true, length: { minimum: 5 }
end

forum/app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :posts
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

forum/app/models/user.rb
class User < ApplicationRecord
  has_one :profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable
end

forum/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

forum/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
    @group.posts.build
  end

  def create 
    params[:group][:title] = params[:group][:posts_attributes]['0'][:title]

    @group = Group.new(group_params) 

		if @group.save
			redirect_to @group
		else
			render 'new'
		end
	end

  def show
    @group = Group.find(params[:id])
  end

  def index
    @groups = Group.all
  end

  private 
  	def group_params
  		params.require(:group).permit(:title, posts_attributes: [:id, :title, :content, :profile_id])
  	end
end

forum/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

forum/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_group
  before_action :set_profile

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
  	@group = Group.find(params[:group_id])
    @post = @group.posts.build
    respond_with(@post)
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @group = Group.find(params[:group_id])
    @post = @group.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @group, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { redirect_to @group, notice: 'Post was not successful, make sure you enter all fields.' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_group
    	@group = Group.find(params[:group_id])
    end

    def set_profile 
    	@profile = current_user.profile
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :group_id, :profile_id)
    end
end

forum/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    if current_user
      @profile = Profile.new
      @exists = Profile.find_by_user_id(current_user.id)
      if @exists
        redirect_to @exists
      end
    else
      redirect_to groups_path
    end
  end

  def create
  	@profile = Profile.new(profile_params)

  	if @profile.save
  		redirect_to @profile
  	else
  		render 'new'
  	end
  end

  def show
    @profile = Profile.find(params[:id])
    @user = User.find(@profile.user_id)
  end

  def index
    @profiles = Profile.all
  end

  def upgradeUser
    if current_user
      if current_user.admin
        @profile = Profile.find(params[:id])
        @user = User.find(@profile.user_id)
        if !@user.admin
          @user.admin = true
          @user.save
        end
      end
    end
    redirect_to @profile
  end

  private
  	def profile_params
  		params.require(:profile).permit(:first,:last,:year,:dorm, :user_id,:avatar)
  	end
  end

forum/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    protected

    def after_sign_up_path_for(resource)
        profiles_new_path
    end
end

forum/app/helpers/application_helper.rb
module ApplicationHelper
end

forum/app/helpers/groups_helper.rb
module GroupsHelper
end

forum/app/helpers/pages_helper.rb
module PagesHelper
end

forum/app/helpers/posts_helper.rb
module PostsHelper
end

forum/app/helpers/profiles_helper.rb
module ProfilesHelper
end

forum/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

forum/app/views/groups/index.html.erb
<!-- This file handles the front page lay-out that lists all of the different Schmack Threads. -->

<h1>Schmack Threads</h1>

<br />
 
<table>
  <tr>
    <th colspan="1"></th>
  </tr>
  <% @groups.each do |group| %>
    <tr>
      <td>
        <div class = "front-card">
          <div class = "front-content">
            <%= link_to group.title, group_path(group) %>
          </div>
        </div>
        <br />
      </td>
    </tr>

  <% end %>
</table>

<br />
<br />

<%- if current_user %>
  <%= link_to 'Make a New Thread!', new_group_path %>
<% end %>

forum/app/views/groups/new.html.erb
<h1>New Thread</h1>

<%= form_with model: @group, local: true do |form| %>
 
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@group.errors.count, "error") %> prohibited
        this thread from being saved:
      </h2>
      <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.fields_for :posts do |posts_form| %>
      <div class="field">
        <%= posts_form.label :title %>
        <%= posts_form.text_field :title, id: :post_title %>
      </div>

      <div class="field">
        <%= posts_form.label :content %>
        <%= posts_form.text_area :content, id: :post_content %>
      </div>

      <div>
        <%= posts_form.hidden_field :profile_id, :value => current_user.profile.id %>
      </div>
    <% end %>
  </p>

  <%= form.hidden_field :title, id: :post_title %>

  <p>
    <%= form.submit :Post!%>
  </p>
 
<% end %>

<%= link_to 'Back', root_path %>

forum/app/views/groups/show.html.erb
<!-- This file handles the general display for a particular Schmack thread. -->

<div class = "title">
  <strong><%= @group.title %></strong>
</div>

<%= render @group.posts %>

<%- if current_user %>
  <h2>Create a New Post</h2>
  <%= render 'posts/form', group: @group %>
<% end %>

<%= link_to 'Back', groups_path %>

forum/app/views/layouts/application.html.erb
<!-- The code for this file was almost entirely based off of the navigation bar for the Bare
    bootstrap template as it was modified for the tutorial found at this linK: https://www.youtube.com/watch?v=MpFO4Zr0EPE -->

<!DOCTYPE html>
<html>
  <head>
    <title>Schmack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <!-- Navigation -->
        <nav class = "navbar navbar-inverse navbar-fixed-top" role = "navigation">
            <div class = "container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class = "navbar-header">
                    <button type = "button" class = "navbar-toggle" data-toggle = "collapse"
                    data-target = "#bs-example-navbar-collapse-1">
                        <span class+"sr-only"> Toggle navigation </span>
                        <span class = "icon-bar"></span>
                        <span class = "icon-bar"></span>
                        <span class = "icon-bar"></span>
                    </button>
                    <%= link_to "Schmack", root_url, class: "navbar-brand" %>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class = "nav navbar-nav navbar-right" id = "bs-example-navbar-collapse-1">
                    <li>
                        <%= link_to "About", pages_about_path %>
                    </li>

                    <%- if current_user %>
                        <%- if current_user.profile %>
                        <li>
                            <%= link_to "My Profile", profile_path(current_user.profile.id) %>
                        </li>
                        <% end %>
                    <li>
                        <%= link_to "Logout", destroy_user_session_path, method: :delete,
                        data:{ confirm: "Are you sure?" } %>
                    </li>

                    <% else %>
                    <li>
                        <%= link_to "Login", new_user_session_path %>
                    </li>
                    <li>
                        <%= link_to "Register", new_user_registration_path %>
                    </li>

                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
        <div class="container">

            <div class="row">
                <div class="col-lg-12 text-center">
                    <% flash.each do |a, b| %>
                        <div class='alert alert-success'> <%= b %> </div>
                    <% end %>
                    <%= yield %>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
      <style>body{padding-top:70px;}</style>
  </body>
</html>

forum/app/views/pages/about.html.erb
<h1>About</h1>
<p>Welcome to Schmack 2: The Re-Schmackening! This is a message board for current, third-floor, and dead residents of East Dorm at Harvey Mudd College to discuss whatever they want! Feel free to start a thread about whatever you want or comment on any thread that interests you. We only have one requirement: that you must enter an internym for every post!</p>

<p style = "font-weight: bold; text-decoration: underline"> Question and Answer </p>

<p>Q: Is this website moderated?</p>

<p>A: Yes! However, as minimally as possible. Talk about whatever you want, just don't be toxic to anyone.</p>

<p>Q: What can we talk about?</p>

<p>A: Anything! Just be a reasonable human being.</p>

<p>Q: Why do we have to have an internym?</p>

<p>A: Because this wouldn't be an East Dorm Chat without pedantic rules.</p>

<p>Q: Who can sign up?</p>

<p>A: Anyone! Although most of the discussion will probably pertain to Harvey Mudd College and East Dorm.</p>

<p style = "font-weight: bold; text-decoration: underline">Authors</p>

<p>Evan "I wrote this page so I put myself first" Amason</p>
<p>Jake "First name actually Marvin" Palanker</p>
<p>Sara "At the time of writing, also working on making the other pages exist" McAllister</p>

forum/app/views/posts/_form.html.erb
<%= form_for([@group, @group.posts.build]) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>

  <div>
    <%= form.hidden_field :profile_id, :value => current_user.profile.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

forum/app/views/posts/_post.html.erb
<!-- This file handles the styling for the individual posts in individual threads. -->

<p>
  <table>
    <tr>
      <td>
        <div class = "profile-card">
          <div class = "content">
            <strong><%= link_to (post.profile.first + " " + post.profile.last), profile_path(post.profile) %></strong>
            <br>
            <%= post.profile.user.email %>
            <br>
            <%= image_tag post.profile.avatar.url(:thumb) %>
          </div>
        </div>
      </td>
      <td>
        <div class = "card">
          <div class = "content">
            <u><strong><%= post.title %></strong></u>
            <br>
            <%= post.content %>
          </div>
        </div>
      </td>
    </tr>
  </table>
</p>

forum/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

forum/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.group %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

forum/app/views/posts/new.html.erb
<h1>New Post</h1>

<p>
  <strong>Title:</strong>
  <%= @group.title %>
</p>

<%= render 'form', group: @group %>

<%= link_to 'Back', @group %>

forum/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


    <p>
        <strong>Title:</strong>
        <%= @post.title %>
    </p>

    <p>
        <strong>Content:</strong>
        <%= @post.content %>
    </p>

    <p>
        <strong>Group:</strong>
        <%= @post.group %>
    </p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

forum/app/views/profiles/create.html.erb
<h1>Profiles#create</h1>
<p>Find me in app/views/profiles/create.html.erb</p>
<%= form_for @profile, html: { multipart: true } do |f| %>
	<div>
    <%= f.label :first %>
		<br><%= f.text_field :first %>
		<br>
		<%= f.label :last %>
		<br><%= f.text_field :last %>
		<br>
    <%= f.label :dorm %>
		<br><%= f.text_field :dorm %>
		<br>
		<%= f.label :year %>
		<br><%= f.text_field :year %>
		<br>
    <%= f.hidden_field :user_id, value: current_user.id%>
		<%= f.submit %>
	</div>
<%end%>

forum/app/views/profiles/edit.html.erb
<h1>Profiles#edit</h1>
<p>Find me in app/views/profiles/edit.html.erb</p>

forum/app/views/profiles/new.html.erb
<h1>Create Your Profile!</h1>
<%= form_with model: @profile, local: true do |f| %>
	<div>
    <%= f.label(:first, 'First Half of Name') %>
		<br><%= f.text_field :first %>
		<br>
		<br>
		<%= f.label(:last, 'Last Half of Name') %>
		<br><%= f.text_field :last %>
		<br>
		<br>
    <%= f.label :dorm %>
		<br><%= f.text_field :dorm %>
		<br>
		<br>
		<%= f.label(:year, 'Class Year') %>
		<br><%= f.text_field :year %>
		<br>
		<%= f.hidden_field :user_id, value: current_user.id %>
		<br>
			<%= f.label(:avatar, 'Profile Picture') %>
  			<%= f.file_field :avatar, :class => "profilePhotoInput" %>
		<br>
		<%= f.submit %>
	</div>
<%end%>

<%= @exists %>

forum/app/views/profiles/show.html.erb
<h1><%= @profile.first %> <%= @profile.last %>'s Profile</h1>
<p>
  <%= image_tag @profile.avatar.url(:medium) %>
</p>
<p>
  <div class = "profile-display">
<table style="width:30%">
 <tr>
   <td><strong>Name:</strong></td>
   <td><%= @profile.first %> <%= @profile.last %></td>
 </tr>
 <tr>
   <td><strong>Email:</strong></td> 
   <td><%= @user.email %></td>
 </tr>
 <tr>
   <td><strong>Year:</strong></td>
   <td><%= @profile.year %></td>
 </tr>
 <tr>
   <td><strong>Dorm:</strong></td>
   <td><%= @profile.dorm %></td>
 </tr>
</table>
</div>
</p>

<%- if current_user %>
  <%- if current_user.admin %>
    <strong> You're an admin </strong><br>
    <%- if @user.admin %>
      <strong> This user is already an admin </strong>
    <%- else %>
      <strong> This users is not an admin </strong>
    <% end %><br>
    <%= link_to 'Upgrade user to Admin', profiles_upgradeUser_path(:id => @profile.id), method: :get %>
  <% end %>
<% end %>